### ISSUE TITLE
Click handlers are not firing

### ISSUE THREAD

**Issue by raviada** [Gabrielr47/pickList#1]
I am loading the pickList.js after jquery lib. I got the UI show up with two lists, but the button click handlers not firing when I click on any of the buttons. any ideas what is happening?

Thanks for such a simple pick list, it is exactly what I needed but I spent almost an hour debugging it.

**Comment by gabriel-rodrigues-42** [comment]
Hi, thanks for notify me, it's fixed in the last version, have a demo of this here: https://jsfiddle.net/gabrielr47/13f7Lrb1/1/

If you have any question or suggestion is only talk.
